components/Footer/index.tsx
cypress/integration/pages/about.ts

Update Footer Links

---

pages/faq.tsx

Updating faq with question about KYC
Tested locally 
No

Updating faq with question about KYC

---

components/FAQ/QuestionAnswer.tsx
components/FAQ/styles.module.css
pages/faq.tsx

Linkable FAQ section
tested on local 
No

Linkable FAQ section

---

pages/faq.tsx

Master barfed [here](https://vercel.com/ironfish/website-testnet/DGhSsGryXts4BiCar3vwqiQGHrLA)

fix master

---

components/About/data.tsx

Comment out an NFT category
None
```
[x] Nope
```

no transactions for NFTs

---

components/Navbar/Links.tsx
cypress/integration/pages/about.ts

We have a roadmap but its discoverability is not great (it's a single link in one of the subsections on the homepage). This PR adds a top-level link to the navbar.
Change to the website navbar can be found here: https://github.com/iron-fish/website/pull/135 
Tested it locally 
No

Adding roadmap in navbar

---

pages/faq.tsx

Changed text
Read
```
[x] No
```

Update FAQ language

---

hooks/usePaginatedEvents.ts
pages/users/[id].tsx

Updates the user page to fetch data on the client rather than on the server.
There isn't much test data on staging anymore, but so far I've tested that the user page loads.
```
[ ] Yes
[x] No
```

Load user page data client-side

---

.env.template

You cannot use production because of CORS errors
```
[ ] Yes
```

Change .env.template to use staging

---

apiClient/client.ts
hooks/useLogin.ts

Each commit is a different small cleanup, and I explain each one in the comments of the PR.
Will run it locally `NEXT_PUBLIC_LOCAL_USER` as false, and will force various error cases.
```
[ ] Yes
```

Cleanup to useLogin hook

---

pages/leaderboard.tsx

Updated the leaderboard CTA
Reading
Nope nope

IRO-1397 - Update Leaderboard CTA

---

components/About/data.tsx
cypress/integration/pages/about.ts

Defining points for promoting the testnet and contributing to the cmmunity categories
(and same for Contributing to the Community section) 
Looked at it on localhost
```
[X] No
[ ] Yes
```

Defining points for testnet categories

---

components/OffsetBorder/Box.tsx
components/OffsetBorder/CustomBox.tsx
components/OffsetBorder/index.tsx
components/PageBanner/index.tsx
components/leaderboard/CountdownTimer.tsx
pages/leaderboard.tsx
tailwind.config.js
utils/date.ts

See if the countdown timer is useful / provides an affordance
Nope

IRO-1396 - Add weekly countdown timer

---

components/About/CallToAction.tsx
components/About/data.tsx

Tested locally 
```
[X] No
[ ] Yes
```

Adding a link to examples for points

---

pages/users/[id].tsx

Fixes the Weekly values being zero (described https://github.com/iron-fish/website-testnet/pull/179#issuecomment-1033399719)
See the page
Nope

Fix Weekly Points value

---

apiClient/types.ts
pages/about.tsx
pages/users/[id].tsx
tailwind.config.js

Show a date, win a prize
Look
```
[ ] Yes
[x] Nope
```

IRO-1553 - Show when users joined the testnet

---

apiClient/client.ts
apiClient/types.ts
components/user/Tabs/SettingsContent.tsx
hooks/useLocalLogin.ts
pages/signup.tsx
utils/forms.ts

Go to `/signup` and sign up with a github field!
Go to `/users/x?tab=settings` (where x is your id) and change your github details!
Nope

Add github field

---

components/leaderboard/LeaderboardRow.tsx
pages/leaderboard.tsx

Adjusted the Search + Filter functionality on the leaderboard to be more helpful at small sizes.
👀 
```
[ ] Yes
[x] Nope
```

IRO-1529 Search and Filter

---

hooks/useLocalLogin.ts
package-scripts.js
utils/forms.ts

Fix https://github.com/iron-fish/website-testnet/pull/196#issuecomment-1058654489

Fix the error on a missing github field

---

pages/leaderboard.tsx

Sliced https://github.com/iron-fish/website-testnet/pull/195 apart for ease of review

Leaderboard only

---

pages/about.tsx

Sliced https://github.com/iron-fish/website-testnet/pull/195 apart for ease of review

About only

---

package-scripts.js
utils/forms.ts

Trying to fix the behavior that seems to keep cropping up here: https://github.com/iron-fish/website-testnet/pull/196

Github field bug

---

components/Navbar/LoginButton.module.css
components/Navbar/LoginButton.tsx

Described in ﻿https://github.com/iron-fish/website-testnet/issues/209 -- the "Sign Out" button has stopped working on mobile.
1. Log in
2. View on mobile / small breakpoint
3. Open Menu
4. Log Out
```
[ ] Yes
[x] Nope
```

Signout button doesn't work on mobile

---

components/About/data.tsx
components/Footer/index.tsx
cypress/integration/pages/about.ts
pages/faq.tsx
pages/signup.tsx

`s#https://discord.gg/EkQkEcm8DH#https://discord.gg/ironfish#g`
Click?
Is this a breaking change? If yes, add notes below on why this is breaking and what additional work is required, if any.
```
[ ] Yes
[x] No
```

use discord.gg/ironfish

---

apiClient/client.ts
apiClient/types.ts
components/PaginationButton.tsx
hooks/usePaginatedUsers.ts
pages/leaderboard.tsx
pages/users/[id].tsx

Make `/leaderboard` data paginated.
👀 
```
[ ] Yes
[x] Nope
```

IRO-1399 - Leaderboard Pagination

---

components/About/CallToAction.tsx
components/About/data.tsx
components/page-types.ts
cypress/integration/pages/about.ts
pages/_app.tsx
pages/about.tsx
pages/community.tsx
pages/debug-user.tsx
pages/faq.tsx
pages/index.tsx
pages/leaderboard.tsx
pages/login.tsx
pages/logout.tsx
pages/signup.tsx

Redoing the changes from the other PR
👀 
```
[ ] Yes
[x] No
```

End phase 1

---

pages/_app.tsx

I saw this value was true, so I set it to false and wasn't sure why it
wasn't working. This should fix this pitfall for anyone else who hasn't
read through the code.
Printed the value out and changed it a few times
```
[ ] Yes
```

Fix NEXT_PUBLIC_LOCAL_USER parsing false

---

pages/faq.tsx

Phase 2 FAQ
```
[ ] Yes
[x] NO
```

Phase 2 FAQ

---

.env.template
apiClient/client.ts
components/About/CallToAction.tsx
components/About/data.tsx
cypress/integration/pages/about.ts
pages/about.tsx

Updating copy for the phase2 about page
Local
```
[X] No
[ ] Yes
```

Updating copy for the phase2 about page

---

pages/faq.tsx

Removing an extra period

---

pages/faq.tsx
utils/scroll.ts

@lwisne noticed that the deep links had stopped working on the FAQ page. This fixes them.
`/faq#transaction-points`
```
[ ] Yes
[x] Nein
```

Scroll to #id on FAQ page

---

components/Navbar/index.tsx

adds May 10th to top banner
```
[ ] Yes
[x] NO
```

add date to top banner

---

components/user/Tabs/AllTimeContent.tsx
pages/leaderboard.tsx

Temporarily remove metrics that aren't reset, marking each with a Linear ticket.
```
[ ] Yes
```

zero out metrics

---

components/About/data.tsx

Adjusting the point economy based on discussion
```
[ ] Yes
```

Adjust the coins point economy

---

components/Form/TextField.tsx
hooks/useForm.ts
pages/leaderboard.tsx
pages/signup.tsx

Form field update to support `explanation` prop

Phase 2 updates

---

components/About/data.tsx
components/Navbar/index.tsx
pages/faq.tsx
pages/leaderboard.tsx

add exact time to website

---

components/About/data.tsx
components/Navbar/index.tsx
pages/faq.tsx
pages/leaderboard.tsx

Staging -> Master

---

components/About/Phase.tsx

About Page container height

---

pages/leaderboard.tsx

The leaderboard copy references net promoters, so I wanted to take that specific reference out of there. Open to other opinions on better copy.
Also this is targeted at master, not sure whether it'd be better to go into staging.
```
[ ] Yes
```

Change the leaderboard description slightly

---

.gitpartyrc
.husky/pre-commit
README.md
package-scripts.js
package.json
yarn.lock

Git supports adding your own local hooks. You don't need to check these in.
Make a commit
```
[ ] Yes
```

Remove husky hooks from repository

---

components/Navbar/Links.tsx
cypress/integration/pages/about.ts

remove roadmap links

---

components/Navbar/Links.tsx
cypress/integration/pages/about.ts

re-add roadmap

---

components/About/Phase.tsx
components/About/data.tsx

Reverts iron-fish/website-testnet#290

revert: "STAGING -> MASTER"

---

components/About/data.tsx

Reverts iron-fish/website-testnet#288

revert: "fix: retroactively update rewards cards"

---

components/About/Phase.tsx

fix: remove coin counts to remove ambiguity of coins

---

pages/faq.tsx

Updates the FAQs for corresponding phase 3 website.
```
[ ] Yes
```

chore: update faqs for phase 3

---

components/About/data.tsx
cypress/integration/pages/about.ts
pages/about.tsx

Update cards for phase 3. Add multiasset card
```
[ ] Yes
```

chore: update cards for phase 3

---

pages/faq.tsx

chore: faq updates

---

components/About/CallToAction.tsx
components/About/Phase.tsx
components/About/data.tsx
components/user/Tabs/AllTimeContent.tsx
cypress/integration/pages/about.ts
pages/about.tsx

Updates cards based on mockup.
```
[ ] Yes
```

chore: update masp cards

---

pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

Change countdown to end of deposits

---

components/leaderboard/CountdownTimer.tsx

Do not render timer when it is complete
```
[ ] Yes
```

chore: floor countdown timer

---

pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

Previous TS was pointed toward Dec 28
```
[ ] Yes
```

fix: countdown timer to nov 28 not dec 28

---

components/About/data.tsx

From https://github.com/iron-fish/website-testnet/pull/324
```
[ ] Yes
```

Fix typo in date for phase3

---

apiClient/types.ts
pages/leaderboard.tsx

Add these filters to the leaderboard in preparation for their addition to the API.
```
[ ] Yes
```

Add pool3 and pool4 to leaderboard filters

---

components/About/Phase.tsx
components/About/data.tsx
components/user/Tabs/AllTimeContent.tsx
pages/about.tsx

Review with https://github.com/iron-fish/website-testnet/pull/341/files?diff=split&w=1
- Changed scientific notiation numbers to base10
- Removed code that checked phaseNum = 0
- Removed wrapper objects in data file, it should be data not layout.
```
[ ] Yes
```

Clean up about page phase code

---

components/user/EventRow.tsx
pages/users/[id].tsx

Fix rendering from crashing from future events

---

pages/leaderboard.tsx

Pool3 is just code contributions so we don't need to create an aggregate for this, we can just use that category behind the scenes.
```
[ ] Yes
```

Fix crash with pool3 category

---

components/user/GenericMetricCard.tsx
components/user/Tabs/AllTimeContent.tsx

There were more places that we didnt properly show the rank as NA if the rank was null.
```
[ ] Yes
```

Fix null rank not showing as NA

---

components/About/data.tsx

We decided the point economy
```
[ ] Yes
```

Update points for multi asset

---

pages/faq.tsx

Added these FAQ questions
```
[ ] Yes
```

Add mint, burn, send to FAQ page

---

pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

Change countdown to Wed Jan 18 2023 01:00:00 EST

---

package-scripts.js
package.json

We didn't have a way to clean up lint errors
```
[ ] Yes
```

Add lint:fix command

---

components/About/data.tsx
pages/faq.tsx

Try to add more information about how to participate in phase 3
```
[ ] Yes
```

Update website instructions

---

pages/faq.tsx

Add FAQ for bad data dir

---

pages/faq.tsx

Add FAQ for requesting faucet funds

---

pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

Testnet has started, time to remove countdown.
```
[ ] Yes
```

chore: remove countdown timer from testnet

---

pages/faq.tsx

Clean up the FAQ page

---

pages/faq.tsx

fix: typos on faq

---

components/About/data.tsx

Updating the Google Forms link for users to request points for PRs / Bug Reports 
Manual
No

Updating the Google Forms link for Phase 3 points submissions

---

pages/faq.tsx

Typo fix in faq.tsx
View string change
No
No
```
[ ] Yes
```

Typo fix in faq.tsx

---

pages/signup.tsx

Docs say we need to use an action and verify it in the backend
```
[ ] Yes
```

Add recaptcha action

---

components/About/data.tsx
pages/faq.tsx

FAQ and rule updates

---

pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

https://www.epochconverter.com/
Epoch timestamp: 1677369599
Timestamp in milliseconds: 1677369599000
Date and time (GMT): Saturday, February 25, 2023 11:59:59 PM
https://github.com/iron-fish/website-testnet/pull/372
```
[ ] Yes
```

Add countdown timer for end of phase 3

---

pages/faq.tsx

faq changes for us airdrops

---

components/PageBanner/index.tsx
pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

Disable sign up button

---

pages/about.tsx
pages/faq.tsx
pages/leaderboard.tsx

This reverts commit e1856aa74e8d47df757d45d64b56740daec46639.
```
[ ] Yes
```

Revert "Add countdown timer for end of phase 3 (#394)"

---

components/Airdrop/RewardItem/RewardItem.tsx
pages/dashboard/rewards/index.tsx

Fix points display

---

pages/api/user-points-by-phase.ts

new points API format

---

components/Airdrop/StepSubmitAddress/StepSubmitAddress.tsx

add a warning box about exporting wallet key

---

hooks/useRequireKYC.ts
pages/dashboard/index.tsx
pages/dashboard/rewards/index.tsx

Add hook to redirect user if no KYC

---

pages/faq.tsx

Removes content relating to email changes.
```
[ ] Yes
```

Remove FAQ items relating to email changes

---

components/About/data.tsx

Mark phase 3 ended

---

components/Airdrop/RewardItem/RewardItem.tsx

fix: Selectable pool name text in reward item

---

components/Airdrop/hooks/useApprovalStatusChip.tsx
pages/dashboard/index.tsx
pages/dashboard/rewards/index.tsx

- Displays reason for KYC rejection if status is TRY_AGAIN
Manual
```
[ ] Yes
```

Show reason for TRY_AGAIN status

---

components/Airdrop/KYCSteps/StepSubmitAddress.tsx
components/Airdrop/WalletAddress/WalletAddress.tsx

We refer to this as public address so we shouldnt use two names.
```
[ ] Yes
```

Rename wallet address to public address

---

components/Airdrop/WalletAddress/WalletAddress.tsx

This is the new simplified flow from figma.
```
[ ] Yes
```

Here is the new public address modal from figma

---

pages/dashboard/rewards/index.tsx

Currently we still show warnings 
test in staging
```
[ ] Yes
```

fix: if success we shouldn't show warnings. period.

---

components/Airdrop/WalletAddress/WalletAddress.tsx
pages/dashboard/rewards/index.tsx

Small typos in copy

---

components/Navbar/Links.tsx

Rm roadmap in navbar since this link doesnt work now

---

pages/callback.tsx
pages/login.tsx

Update redirect to dashboard after login
local
```
[ ] Yes
```
@dgca

Update redirect to dashboard

---

hooks/useLogin.ts

Check id in response instead of status code

---

apiClient/client.ts
pages/logout.tsx

Call /logout endpoint to empty jwt token in cookie
```
[ ] Yes
```
@dgca @rohanjadvani

Call server to logout

---

components/Airdrop/hooks/useApprovalStatusChip.tsx

Fix kyc status, airdrop ended -> kyc ended
