iron-fish/website-testnet

components/user/Tabs/SettingsContent.tsx, components/user/Tabs/index.tsx, pages/users/[id].tsx
The settings tab currently shows up on every user page when you're logged in, which led to some confusion around whether you're viewing settings for that user or for the logged-in user. This change makes it only appear when the authed user ID matches the user page's user ID.
I renamed a bunch of props here to what I thought was more clear, I'm fine rolling those renames back if it doesn't seem like an improvement 👍 
Fixes #119
=> Hide settings tab on non-authed user page

.env.template, hooks/useLogin.ts, pages/_app.tsx
We've made the decision (see previous [Login PR](https://github.com/iron-fish/website-testnet/pull/126#discussion_r764183123)) to make some of our UI hang in a loading state until it hears back from Magic Link. This is good in non-local environments, but locally it's a bit of a PITA to use things.
Make sure this doesn't change anything except locally.
No, unless you set `NEXT_PUBLIC_LOCAL_USER` to true in production.
=> Support local editing with user fixture

components/Form/TextField.tsx, components/ResponsiveToolkit/index.tsx, hooks/useForm.ts, pages/login.tsx, pages/signup.tsx, utils/forms.ts
Now form fields can specify their `WHITESPACE` rules:
1. `WHITESPACE.DEFAULT` - This keeps the behavior of all extant things
2. `WHITESPACE.TRIMMED` - This implicitly trims (removes trailing + leading whitespace) strings, so if you write `     cooluser     ` (note the trailing spaces) the system only registers `cooluser` as the value.
3. `WHITESPACE.BANNED` - This prevents any whitespace from being entered on a given form.
1. Go to: [Sign Up](https://website-testnet-git-trim-yo-strings-ironfish.vercel.app/signup) (you may need to log out first)
2. Try entering spaces on the *Email* or *Social* (Discord / Telegram) fields, they will not be allowed.
3. Spaces can be entered on the *Graffiti* field, they will be allowed to be entered but the resulting value (which will be in the email you …
=> IRO-1402: Fields can set whitespace controls

pages/faq.tsx
We have a lot of people asking why they're not getting points for mined blocks. A lot of the time this is due to the miner displaying a log message that a block has been successfully mined, and then that block not being accepted by the network (presumably because there's a heavier competing block in the same time span). This PR adds an FAQ to help with that confusion. 
Tested locally
No
=> Adding an FAQ about mined forked blocks

next-env.d.ts, package.json, yarn.lock
Starting to address the automated security updates we're behind on: 
https://github.com/iron-fish/website-testnet/security/dependabot
Run the site, `next` should still work. The `gitlog` usage was tied to a developer experience thing and won't affect any part of the build process.
Nein.
=> Address two security vulnerabilities

package-scripts.js
gitparty was removed in #155, so this script shouldn't be needed now either.
None needed.
```
[ ] Yes
[x] No
```
=> Remove gitparty from package-scripts

pages/leaderboard.tsx
This page will watch the entire field from useField()  instead of
the field value, which the form is null, and then not null because
of how it's written in a useEffect(). This cause us to incur 2x
traffic to our API when users load the page. Now we only watch 
the value, which prevents the double request from happening to
the leaderboard.
Tested locally
```
[ ] Yes
```
=> Fix leaderboard watching field causing 2x requests

hooks/useLocalLogin.ts, hooks/useLogin.ts, pages/_app.tsx
useLocalLogin returned an inconsitent return type from useLogin. This
fixes that, and moves it into its own file so we have 1 hook per file as
the code base seems to use.
Ran code with both hooks
```
[ ] Yes
```
=> Type useLocalLogin

pages/leaderboard.tsx
Removed the server side rendering that ignored the first search if the results came from the server side props.
Tested locally
```
[ ] Yes
```
=> Remove unused server-side rendering

components/About/data.tsx, components/user/Tabs/WeeklyContent.tsx, components/user/Tabs/WeeklyMetricCard.tsx
Updating the "Earn up to 5000 points per week" on the About page was pretty straightforward. For the weekly stats page, since PRs can be awarded variable amounts of points, it doesn't exactly work to show the maximum number of PRs that can be submitted per week -- I changed it to instead show the points as the major value, and the point value max. Then underneath, it shows the instances of each event (i.e. number of blocks mined, number of PRs submitted)
Load up some users and check that their pages display correctly. You can include more data into the data that's shown in the current week on staging by editing the `getWeeklyStart` function locally.
```
[ ] Yes
```
=> Increase weekly PR points to 5000

components/About/CallToAction.tsx, cypress/integration/pages/about.ts
The link buttons weren't going to the right place, they were linking to the HREF of the call to action and not the claim page.
https://website-testnet-git-fix-links-ironfish.vercel.app/about
Tested manually and updated broken tests
```
[ ] Yes
```
=> Fixed claim points buttons linking to the wrong place

components/About/CallToAction.tsx
Before: 
After:
Tested locally. Looks 👌
```
[X] No
[ ] Yes
```
=> Fixing margins for testnet about sections

.github/workflows/e2e.yml, cypress/integration/pages/about.ts
Integration tests stopped working, because in part:
1. We used to rely upon `patrickedqvist/wait-for-vercel-preview@master`, but now we evidently have to use: `patrickedqvist/wait-for-vercel-preview@v1.2.0`
2. Because the tests were broken, the integration test snapshots had to be updated.
Check the automated tests.
Nope
=> Fix E2E tests

components/leaderboard/CountdownTimer.tsx, components/user/EventRow.tsx, utils/date.ts, utils/events.ts
Events from before the testnet are valid and should be rendered.
Now they are.
1. Add events to a user before Dec. 1, 2021
2. They will render like this: ![CleanShot 2022-02-11 at 09 36 11](https://user-images.githubusercontent.com/18919/153640856-b9c0b882-68f6-4112-b563-7e6e3ffa2e1e.png)
3. Profit ?
Nope.
=> IRO-1541 - Render events whose occurred_at value is before Testnet started

pages/leaderboard.tsx
I kept clicking in the invisible region and I couldn't find where the
bounds of the search were. This fixes that issue so it makes it so you
can click anywhere in the box.
Clicked around, recorded gif.
```
[ ] Yes
```
=> Make leaderboard search full width

components/Form/Select.module.css, components/leaderboard/LeaderboardRow.tsx, pages/leaderboard.tsx
Fixing up issue referenced at https://github.com/iron-fish/website-testnet/issues/184. Changes made in this PR
- add extra padding in `<Select>` so text doesn't overlap with arrow on mobile
- `<Select>` arrow height was a bit off
- Leaderboard looks much better on mobile now
before:
after:
```
[ ] Yes
[x] No
```
=> fix leaderboard page on mobile

components/user/Tabs/AllTimeContent.tsx, components/user/Tabs/WeeklyContent.tsx
Just changing "Community Contributions" string to "Community" in the weekly/global view 
Local
```
[x] No
[ ] Yes
```
=> Changing Community Contributions string to just Community

apiClient/client.ts, hooks/useForm.ts
We used to be sending `{github: ''}`, now we are not.
Sign up
Is this a breaking change? If yes, add notes below on why this is breaking and what additional work is required, if any.
```
[ ] Yes
[x] No
```
=> Fix github field sending empty string

pages/leaderboard.tsx
I kept clicking in the invisible region and I couldn't find where the
bounds of the search were. This fixes that issue so it makes it so you
can click anywhere in the box.
Clicked in search
```
[ ] Yes
```
=> Make leaderboard search full width (#188)

pages/users/[id].tsx
Change the sizing of the graffiti and prevent second line from showing up at large breakpoints.
Before:
After:
👀 
```
[ ] Yes
[x] Nope
```
=> Responsive one-offs

apiClient/client.ts, apiClient/types.ts, pages/users/[id].tsx
If you go to a user ID which doesn't exist, our frontend didn't deal with the missing data correctly:
e.g. testnet.ironfish.network/users/100000
Go to `/users/[some-number-which-doesn't-exist-as-a-user-id]`
No, it's a fixing change.
=> handle unknown users

apiClient/client.ts, apiClient/types.ts, components/About/data.tsx, components/Footer/index.tsx, components/PaginationButton.tsx, cypress/integration/pages/about.ts, hooks/usePaginatedUsers.ts, pages/faq.tsx, pages/leaderboard.tsx, pages/signup.tsx, pages/users/[id].tsx
- [Discord links update](https://github.com/iron-fish/website-testnet/pull/211)
- [User Pagination](https://github.com/iron-fish/website-testnet/pull/205)
- [Search / Filter updates](https://github.com/iron-fish/website-testnet/pull/202) for mobile which somehow got eaten last release
- Paginate back and forth on `/leaderboard` 
- Click discord links (if you are so inclined)
- Check out the Search / Filter UI on `/leaderboard` at a mobile width, it should look like this: 
```
[ ] Yes
[x] No
```
=> Staging -> Master

pages/leaderboard.tsx
The link to phase 1 goes to the wrong URL, because it doesn't have a
protocol so the browser treats it as a relative URL.
View the link on the leaderboard.
```
[ ] Yes
```
=> Fix leaderboard link to phase 1

components/Form/FormRow.tsx, components/Form/TextField.tsx, hooks/useForm.ts, pages/login.tsx
1. Set the internal `touched` value based on a given `defaultValue`
2. Segment validation as a separate `useEffect`
This previously [merged PR](https://github.com/iron-fish/website-testnet/pull/225) was a quick fix. With this PR's changes, we can see the same behavior without the one-off `useEffect`.
1. Working: https://website-testnet-git-update-form-checkery-ironfish.vercel.app/login?email=cool@gmail.com
2. Also working (but invalid email): https://website-testnet-git-update-form-checkery-ironfish.vercel.app/login?email=coolcoolcoolemail
```
[ ] Yes
[x] Hopefully not
```
=> Update useForm `defaultValue` behaviors

apiClient/types.ts, components/user/EventRow.tsx
- Change the key from `hash` to `transaction_hash` for the EventRow summaries
- Updated link so that it correctly formats the transaction_hash/block_hash
=> Update key for transaction events

pages/users/[id].tsx
It was counting up individual categories and missing some, instead of
using the users total points.
**Broken**
**Fixed**
Run and look at points for a user that has pull request points
```
[ ] Yes
```
=> Fix profile not using user total points

components/user/EventRow.tsx
On the leaderboard's User page, link of the successfully processed transaction was leading to a 404 page on Explorer (e.g. https://explorer.ironfish.network/transaction/1d2c2a8ad5b0194381d7086d88e9b43a30548c7cde1cdfbaf97792213f098720/000000000009668ee2c696ae3aefe1fba9524d6cf7350dee37bbb784fb461c34) 
Fixed by removing the last part of URL (block hash)
```
```
=> Fix transaction URL leading to Explorer

components/Footer/index.tsx
it is a good practice to open external links in a new tab. But currently, the links to social media in the footer are opening in the same tab. In this change added target="_blank" to make this small improvement.
```
[ ] Yes
```
=> Make opening outside links in the new tab.

components/Loader/index.module.css
noticed that the ironfish loading svg is not centered properly.
=> fix: ironfish loading svg alignment

components/About/Phase.tsx, components/About/data.tsx
Remove explicit references to coins in accordance with legal guidance.
Split out points for code contributors and pools. 
Pool 3 will retroactively apply for all code contributions during Phase 1 and Phase 2.
```
[ ] Yes
```
=> fix: retroactive changes for tokens and pools

components/About/data.tsx
Updates rewards card to retroactively:
1) Remove explicit token conversion rate to adhere to legal guidance.
2) Describe second code contribution point pool for those who contributed during phase 1.
```
[ ] Yes
```
=> fix: retroactively update rewards cards

components/user/Tabs/index.tsx, pages/users/[id].tsx
We're still making API calls to fetch weekly metrics and the metrics config, even though Phase 2 doesn't have weekly events, and we're not actually displaying the data anywhere.
Since these can be fairly heavy queries, it's best to remove them.
```
[ ] Yes
```
=> Remove fetching weekly metrics and metrics config

pages/users/[id].tsx
The user page perma-loads even after requests time out. We may as well redirect to the leaderboard rather than leaving the page stuck there forever not doing anything.
```
[ ] Yes
```
=> Redirect to the leaderboard when requests time out

components/PageBanner/index.tsx, components/leaderboard/CountdownTimer.tsx, pages/about.tsx, pages/faq.tsx, pages/leaderboard.tsx
=> feat: add countdown timer for end of phase 2

components/About/data.tsx, components/user/Tabs/AllTimeContent.tsx
The pools were wrong, and were showing phase 2 pools. This will show phase 3 pools now.
```
[ ] Yes
```
=> User pools

pages/users/[id].tsx
We have an error when opening the user metrics page.
```
TypeError: Cannot read properties of null (reading 'toLocaleString')
at De ([id]-21bb4c7fe40e7902.js:1:49840)
```
This change is a fix for this problem.
AFTER FIX:
```
[ ] Yes
```
=> Fixed crash while open user stats

styles/globals.css
Input outline styling improved
This was the earlier design:
After this change it'll look like this:
Pr screencast:
[Desktop](https://drive.google.com/file/d/1NhgV3lfAAThTxuAGnBW5pl588CExce0p/view?usp=sharing)
[Mobile](https://drive.google.com/file/d/1vp5EKJ6y1xibTnSsBmjrpugdx_YemauD/view?usp=sharing)
Production screencast:
[Desktop](https://drive.google.com/file/d/1UgiRQzmi5j7Z2o-W3Qu8808UitpbBigD/view?usp=sharing)
```
[ ] Yes
```
=> Input outline styling improved

README.md, pages/faq.tsx
1 - update README env to be same as `.env.template` file
2 - FAQ has some typos. shouldn't be `burn` everywhere.
```
[ ] Yes
```
=> Fix FAQ and README

pages/users/[id].tsx
This date was invalid because it had the 18th month of 2023.
*Before*
*After*
```
[ ] Yes
```
=> Change start time to january 18th

pages/leaderboard.tsx
The 300 is a little aggressive, I often find it searching before I've finished typing unless I know exactly what I'm typing.
```
[ ] Yes
```
=> fix: increase leaderboard search from 300 to 500

components/Footer/index.tsx
I have found an issue on the testnet website where the displayed Discord social media link is expired. I strongly recommend using the updated URL, https://discord.ironfish.network/. Please fix this issue as soon as possible to avoid any inconvenience for users who want to join ironfish community.
=> Expired Discord link on Testnet website

components/user/EventRow.tsx
We have an issue with links to explorer for MINT|BURN|SENT events.
Current result:
We cannot navigate to explorer. We only can copy transaction hash.
After fix:
The links are clickable and we can navigate to the explorer
And after clicking we see our transaction in explorer
```
[ ] Yes
```
=> Fix link for events from phase3

components/user/EventRow.tsx
In the "activity" table we have snake_case for new activities while based on previous phases looks like it should be regular text
```
[ ] Yes
```
=> Changed SNAKE_CASE text to regular like it done for other categories

components/About/data.tsx, pages/faq.tsx
users need to be running the most recent version of Iron Fish to earn points for hosting a node. there is a one week grace period to update. the website doesn't say anything about this.
adds information on the one week grace period to the phase 3 'About' page, and adds information to the FAQ answer around uptime points.
```
[ ] Yes
```
=> updates testnet website info on uptime points

pages/signup.tsx
Social is not a required field, so we don't need to error if it is untouched. This was causing users to have to click "Sign Up" twice if they did not interact with the discord/telegram input.
Manual testing
```
[ ] Yes
```
=> fix(sign up form): Incorrect telegram/discord validation

components/About/data.tsx
we're ending the testnet early.
removes mentions of the rule requiring 140 points of uptime for mint, burn, and send points to count.
```
[ ] Yes
```
=> removes uptime rule from faq

components/Airdrop/RewardItem/RewardItem.tsx
This shouldn't say Open Source Reward for all pools -- we can just say "Reward".
```
[ ] Yes
```
=> Simplify Reward text on Rewards page

pages/redemption.tsx
We linked this page in https://www.ironfish.network/blog/2023/02/28/testnet-rewards, so we should at least have a redirect for it in case people bookmarked it.
```
[ ] Yes
```
=> Redirect /redemption to /dashboard/rewards

components/Airdrop/types/JumioTypes.ts, pages/dashboard/rewards/index.tsx
The Rewards page shows an empty string for the max number of attempts if an attempt hasn't been made yet. This change defaults the value to three, and also defaults the value of kycAttempts to 0. Also updates the type of the KYC endpoint when no attempt has been made yet.
```
[ ] Yes
```
=> Fix max attempts display on rewards page

components/Airdrop/InfoChip/InfoChip.tsx, components/Airdrop/hooks/useApprovalStatusChip.tsx
=> Fix InfoChip with long line of text inside

components/Airdrop/KYCSteps/StepSubmitAddress.tsx, components/Airdrop/WalletAddress/WalletAddress.tsx, components/Toast/Toast.tsx, pages/dashboard/rewards/index.tsx, tailwind.config.js
Adds a way to edit the previously submitted wallet address on the "/dashboard/rewards" page.
Manual testing
```
[ ] Yes
```
=> Add edit wallet address modal

pages/dashboard/rewards/index.tsx
If user has no points, we don't need to show `TBD`, we can show 0
test in staging
```
[ ] Yes
```
=> fix: show 0 reward for no points in category

components/Airdrop/KYCSteps/StepConfirmJumioStart.tsx
I spoke with skylar about the copy here and we simplified it down and also now link to our new KYC guide.
*Before*
*After*
```
[ ] Yes
```
=> Simplified down KYC copy

components/user/EventRow.tsx
Going forward the mainnet API will be used for mainnet blocks. However we still need to use it for KYC and users to view their profile for a while into mainnet. The user profile contains links to blocks and transactions the user was a part of but these will now be on phase3.explorer.ironfish.testnet NOT explorer.ironfish.testnet. So the links need to change here
```
[ ] Yes
```
=> Link to Phase3 archive for blocks and transactions

apiClient/client.ts
In case of login error, the front end is not read the /me response correctly.
There is one place checking statusCode https://github.com/iron-fish/website-testnet/blob/master/pages/callback.tsx#L34
Another place checking error  https://github.com/iron-fish/website-testnet/blob/master/hooks/useLogin.ts#L65
Add statusCode and error in the /me response
vercel
```
[ ] Yes
```
@dgca @iron-fish/engineering
=> Add error and statusCode in /me response

apiClient/client.ts, hooks/useLogin.ts
The new login flow set jwt token in the cookie, example of cookie string
_ga=GA1.1.1480516078.1663010890; _ga_GJD73W9V3M=GS1.1.1680053950.84.0.1680053950.0.0.0; ironfish_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ5YWp1bi5nYW8xMDA0QGdtYWlsLmNvbSIsImlhdCI6MTY4MDY0OTM5OTU2NywiZXhwIjoxNjgwNjQ5NDg1OTY3fQ.QCRG_2Q30bSYQXAmpAEuPx8XqaNFQ8YbVxBtDWKcyMA
When access the /dashboard with valid jwt token, we should let the user through. This PR adds the logic to check jwt token in LoginContext. It will call backend /me endpoint to validate the token. If /me response has 200 status code, the user pass the auth.
Vercel
```
[ ] Yes
```
@dgca @rohanjadvani
=> Check jwt token in loginContext

hooks/useLogin.ts
Remove the logic to check jwt token value because jwt token is not available in document.cookie.
If magic link token is empty, call getUser endpoint. If the request has the right cookie, this call will succeed.
```
[ ] Yes
```
@dgca
=> Call user api when token is empty

apiClient/client.ts
The fetch /me request does not have cookie because the domains don’t match. The front end is in testnet.ironfish.network and fetch request is in api.ironfish.network. 
Include the cookie in the request header manually
```
[ ] Yes
```
@dgca
=> Include cookie in the request headers

apiClient/client.ts, components/Airdrop/KYCSteps/KYCSteps.tsx, components/Airdrop/hooks/useCreateKycFlow.ts, components/Airdrop/hooks/useGetKycStatus.ts
The jwt token cookies need to be manually included in the request to backend server. 
Add `credentials: 'include'` to all the calls to backend requests.
```
[ ] Yes
```
@dgca @rohanjadvani
=> Include cookies with jwt token for all KYC related backend calls

components/Airdrop/WalletAddress/WalletAddress.tsx, components/Airdrop/hooks/useCreateKycFlow.ts, components/Airdrop/hooks/useGetKycStatus.ts, pages/logout.tsx
When use jwt token, magic link get token function will throw error
```
fetch error Error: Magic RPC Error: [-32603] Internal error: User denied account access.
```
Silence these error so that jwt token can be used.
```
[ ] Yes
```
@dgca
=> Catch error when get magic link token

components/Airdrop/WalletAddress/WalletAddress.tsx
Removes button since we have already set addresses for airdrop.
tests pass
```
[ ] Yes
```
=> feat: disable edit button for public address
